### ISSUE TITLE
Highscore Page Bug

### ISSUE THREAD

**Issue by mirkopleli** [Sybit-Education/Coding-Camp-2020#111]
Die Aktuelle Highscore Seite zeigt eine falsche Punktezahl an.

**Comment by mirkopleli** [comment]
**Firestore Daten sind nicht valide.**
![Bildschirmfoto 2021-04-05 um 12 41 29](https://user-images.githubusercontent.com/29863859/113566119-64368280-960c-11eb-88a9-7344c9c59562.png)

Durch die Anführungszeichen kann die Berechnung nicht richtig durchgeführt werden.
![Bildschirmfoto 2021-04-05 um 12 41 54](https://user-images.githubusercontent.com/29863859/113566182-7d3f3380-960c-11eb-9fa1-2ad456315ef5.png)

**Comment by mirkopleli** [comment]
Die aktuelle Implementierung speichert  beim Anlegen eines Impulses die Punkte als String in Firestore.

**Comment by stritti** [comment]
Vielen Dank für die Korrektur. Das war ja ganz schön versteckt 👍
