### ISSUE TITLE
Lea möchte Impulse mit ihrer Schwester via Whatsapp teilen, um sie darauf aufmerksam zu machen

### ISSUE THREAD

**Issue by nicolajlerch** [Sybit-Education/Coding-Camp-2020#39]

**Comment by stritti** [comment]
Have a look at the awesome article on PWAdvent.dev https://pwadvent.dev/day/2/

**Comment by stritti** [comment]
Mögliche Komponente: https://github.com/GabrielBibiano/vue-navigator-share
