### ISSUE TITLE
Update der App führt zu endlosen Notifikationen 

### ISSUE THREAD

**Issue by enricofranke** [Sybit-Education/Coding-Camp-2020#58]
Wie in der Präsentation schon gesehen wird beim Abmelden ein unendlicher Loop an Vue.Notify gesendet, dass die App momentan Updates bekommt, dies scheint ein Fehler zu sein

**Comment by jonasdegener** [comment]
Bei mir tritt der Fehler nicht auf. Wie genau kann ich diesen triggern?

**Comment by stritti** [comment]
Das liegt nicht am Abmelden, sondern wenn die Dateien der App aktualisiert werden (PWA Notifikation)

**Comment by stritti** [comment]
Already fixed. Not reproducible any more.
