### ISSUE TITLE
Nickname wird zurück gesetzt

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Coding-Camp-2020#63]
Der Nickname Wird immer wieder auf Anonym zurück gesetzt.
Scheint zu passieren, wenn man bestätigt, dass man einen Impuls gemacht hat.

**Comment by jonasdegener** [comment]
Wie genau tritt das Problem auf? Habe es getestet, bei mir klappt alles.

**Comment by stritti** [comment]
Sobald ich einen Impuls als gemacht bestätige, wird es zurück gesetzt.

**Comment by jonasdegener** [comment]
Der Username, den du unter Profil anlegst?

**Comment by jonasdegener** [comment]
@stritti

**Comment by stritti** [comment]
> Der Username, den du unter Profil anlegst?

ja genau. Habe das bemerkt, da ich dann in der Highscore als "Anonymous" stehe.
