### ISSUE TITLE
Assignen funktioniert nicht

### ISSUE THREAD

**Issue by chrisWolter** [Sybit-Education/Coding-Camp-2020#71]
Ich kann keine Karte zu mir assignen. Habe mich mit einem Google Account angemeldet und mir auch einen Display Namen gegeben.

Fehler in der Console:

![image](https://user-images.githubusercontent.com/48556854/100988995-9ea1ed00-3550-11eb-8b40-97caf4715708.png)

**Comment by stritti** [comment]
Das schient ein Problem zu sein, wenn man Initial noch gar keinen Impuls hat
