### ISSUE TITLE
Annehmen/abhacken eines Impulses, führt zur Detailseite des Impulses

### ISSUE THREAD

**Issue by cedi315** [Sybit-Education/Coding-Camp-2020#98]
Wenn man auf das **+** oder ✔ klickt, wird man immer auf die Detailseite geroutet anstatt auf der aktuellen Seite zu bleiben.

**Comment by stritti** [comment]
sollte mit PR https://github.com/Sybit-Education/Coding-Camp-2020/pull/101 behoben sein.
